openapi: 3.0.1
info:
  title: Marketo Engage Rest Approve Used API
  description: Marketo exposes a REST API which allows for remote execution of many of the systems capabilities. From creating programs to bulk lead import, there are many options which allow fine-grained control of a Marketo instance.
  termsOfService: https://www.adobe.com/legal.html
  contact:
    name: Adobe Developer Relations
    url: https://experienceleague.adobe.com/en/docs/marketo-developer/marketo/home
    email: developerfeedback@marketo.com
  license:
    name: API License Agreement
    url: https://experienceleague.adobe.com/en/docs/marketo-developer/marketo/api-license
  version: '1.0'
servers:
- url: https://localhost:8080/
tags:
- name: Used
paths:
  /rest/asset/v1/emailTemplates/{id}/usedBy.json:
    get:
      tags:
      - Used
      summary: Marketo Get Email Template Used By
      description: 'Returns a list of email records which depend on a given email template. Required Permissions: Read-Only Assets, Read-Write Assets'
      operationId: getEmailTemplateUsedByUsingGET
      parameters:
      - name: id
        in: path
        description: Id of the email template
        required: true
        schema:
          type: integer
          format: int32
      - name: offset
        in: query
        description: Integer offset for paging
        schema:
          type: integer
          format: int32
      - name: maxReturn
        in: query
        description: Maximum number of channels to return. Max 200, default 20
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOfEmailTemplateUsedByResponse'
  /rest/asset/v1/form/{id}/usedBy.json:
    get:
      tags:
      - Used
      summary: Marketo Get Form Used By
      description: 'Returns a list of asset records which depend on a given form. Required Permissions: Read-Only Assets, Read-Write Assets'
      operationId: getFormUsedByUsingGET
      parameters:
      - name: id
        in: path
        description: Id of the form
        required: true
        schema:
          type: integer
          format: int32
      - name: offset
        in: query
        description: Integer offset for paging
        schema:
          type: integer
          format: int32
      - name: maxReturn
        in: query
        description: Maximum number of assets to return. Max 200, default 20
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOfFormUsedByResponse'
components:
  schemas:
    FormUsedByResponse:
      required:
      - id
      - name
      - status
      - type
      - updatedAt
      type: object
      properties:
        id:
          type: integer
          description: Id of the asset
          format: int64
        name:
          type: string
          description: Name of the asset
        type:
          type: string
          description: Type of asset
        status:
          type: string
          description: Status filter for draft or approved versions
          enum:
          - approved
          - draft
        updatedAt:
          type: string
          description: Datetime the asset was most recently updated
          format: date-time
    ResponseOfEmailTemplateUsedByResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
        requestId:
          type: string
        result:
          type: array
          items:
            $ref: '#/components/schemas/EmailTemplateUsedByResponse'
        success:
          type: boolean
        warnings:
          type: array
          items:
            type: string
    ResponseOfFormUsedByResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
        requestId:
          type: string
        result:
          type: array
          items:
            $ref: '#/components/schemas/FormUsedByResponse'
        success:
          type: boolean
        warnings:
          type: array
          items:
            type: string
    EmailTemplateUsedByResponse:
      required:
      - id
      - name
      - status
      - type
      - updatedAt
      type: object
      properties:
        id:
          type: integer
          description: Id of the asset
          format: int64
        name:
          type: string
          description: Name of the asset
        type:
          type: string
          description: Type of asset
        status:
          type: string
          description: Status filter for draft or approved versions
          enum:
          - approved
          - draft
        updatedAt:
          type: string
          description: Datetime the asset was most recently updated
          format: date-time
    Error:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: string
          description: Error code of the error. See full list of error codes <a href="https://developers.marketo.com/rest-api/error-codes/">here</a>
        message:
          type: string
          description: Message describing the cause of the error
x-original-swagger-version: '2.0'
