openapi: 3.2.0
info:
  description: Marketo Engage Rest API
  version: '1.0'
  title: Marketo Engage Rest Tokens API
  termsOfService: https://www.adobe.com/legal.html
  contact:
    name: Adobe Developer Relations
    url: https://experienceleague.adobe.com/en/docs/marketo-developer/marketo/home
    email: ''
  license:
    name: API License Agreement
    url: https://experienceleague.adobe.com/en/docs/marketo-developer/marketo/api-license
servers:
- url: https://localhost:8080/
tags:
- name: Tokens
  description: Token Controller
paths:
  /rest/asset/v1/folder/{id}/tokens.json:
    get:
      tags:
      - Tokens
      summary: Get Tokens by Folder Id
      description: 'Retrieves the list of available My Tokens in the target folder. Required Permissions: Read-Only Assets, Read-Write Assets'
      operationId: getTokensByFolderIdUsingGET
      parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: integer
          format: int32
      - name: folderType
        in: query
        description: Type of folder. 'Folder' or 'Program'
        required: false
        schema:
          type: string
          enum:
          - Folder
          - Program
          default: Folder
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOfTokenResponse'
    post:
      tags:
      - Tokens
      summary: Create Token
      description: 'Create or update a token in the parent folder. Required Permissions: Read-Write Assets'
      operationId: addTokenTOFolderUsingPOST
      parameters:
      - name: id
        in: path
        description: Id of the folder to which the token will be associated with
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOfTokenResponse'
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CreateTokenRequest'
        description: createTokenRequest
        required: true
  /rest/asset/v1/folder/{id}/tokens/delete.json:
    post:
      tags:
      - Tokens
      summary: Delete Token by Name
      description: 'Deletes a token with the given name from the parent folder. Required Permissions: Read-Write Assets'
      operationId: deleteTokenByNameUsingPOST
      parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOfIdResponse'
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/DeleteTokenRequest'
        description: deleteTokenRequest
        required: true
components:
  schemas:
    ResponseOfTokenResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
        requestId:
          type: string
        result:
          type: array
          items:
            $ref: '#/components/schemas/TokenResponse'
        success:
          type: boolean
        warnings:
          type: array
          items:
            type: string
    TokenDTO:
      type: object
      properties:
        computedUrl:
          type: string
        name:
          type: string
        type:
          type: string
        value:
          type: string
    Error:
      type: object
      required:
      - code
      - message
      properties:
        code:
          type: string
          description: Error code of the error. See full list of error codes <a href="https://developers.marketo.com/rest-api/error-codes/">here</a>
        message:
          type: string
          description: Message describing the cause of the error
    ResponseOfIdResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
        requestId:
          type: string
        result:
          type: array
          items:
            $ref: '#/components/schemas/IdResponse'
        success:
          type: boolean
        warnings:
          type: array
          items:
            type: string
    CreateTokenRequest:
      type: object
      required:
      - folderType
      - name
      - type
      - value
      properties:
        folderType:
          type: string
          description: Type of folder. 'Folder' or 'Program'
          enum:
          - Program
          - Folder
        name:
          type: string
          description: Name of the token. Max length is 50 characters)
        type:
          type: string
          description: Type of the token
          enum:
          - date
          - number
          - rich text
          - score
          - sfdc campaign
          - text
        value:
          type: string
          description: Value of the token
    DeleteTokenRequest:
      type: object
      properties:
        folderType:
          type: string
          enum:
          - Program
          - Folder
        name:
          type: string
        type:
          type: string
    IdResponse:
      type: object
      required:
      - id
      properties:
        id:
          type: integer
          format: int32
          description: Id of the asset
    TokenResponse:
      type: object
      required:
      - folder
      properties:
        folder:
          type: string
          example: '{"id":1001,"type":"Program"}'
          description: JSON representation of parent folder, with members 'id', and 'type' which may be 'Folder' or 'Program'
        tokens:
          type: array
          description: List of tokens in the folder
          items:
            $ref: '#/components/schemas/TokenDTO'
